version: '1.0.{build}'

environment:
  matrix:
    - RUBY_VERSION: 23
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 23-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile

    - RUBY_VERSION: 23
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 23-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake cuke_linter:ci_build

artifacts:
  - path: testing\reports\**\*.html
  - path: coverage\index.html
