version: '1.0.{build}'

environment:
  matrix:

    # NOTES:
    #   - Ruby 2.3 doesn't seem to work on AppVeyor

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler1.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler2.gemfile

    - RUBY_VERSION: 24
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile
    - RUBY_VERSION: 24-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile
    - RUBY_VERSION: 25
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile
    - RUBY_VERSION: 25-x64
      BUNDLE_GEMFILE: testing/gemfiles/cuke_modeler3.gemfile

# Allow Windows builds to use CRLF as expected by linting tools, etc.
init:
  - git config --global core.autocrlf true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake cuke_linter:ci_build
